const express = require('express');
const studentController = require('../controller/studentController');
const middleware = require('../../utility/verifyToken');
const router = express.Router();
router.post('/',              studentController.newStudent);
router.post('/verify',        studentController.verifyOtp);
router.post('/login',         studentController.login);
router.post('/changePassword',middleware.verifyToken,studentController.changePassword);
router.post('/forgetPassword',studentController.forgetPassword);
router.get('/',               middleware.verifyToken,studentController.findStudent);
router.put('/',               middleware.verifyToken,studentController.updateStudent);
router.delete('/:id',         middleware.verifyToken,studentController.deleteStudent);
module.exports = router;