const express = require('express');
const studentController = require('../controller/studentController');
const middleware = require('../../utility/verifyToken');
const router = express.Router();
router.post('/',studentController.newStudent);
router.post('/verify',studentController.verifyOtp);
router.post('/login',studentController.login);
router.post('/changePassword',middleware.verifyToken,studentController.changePassword);
router.post('/forgetPassword',middleware.verifyToken,studentController.forgetPassword);
router.get('/',studentController.findStudent);
router.put('/',studentController.updateStudent);
router.delete('/:id',studentController.deleteStudent);
module.exports = router;